import fresh_tomatoes
import media
""" This file was mostly written in class: Programmings Foundations for Python. However it was modified by Unnar Thor Bachmann to 56
    Icelandic movies to the project.
"""
#An array containing each instance of the movie class.
movies = [
media.Movie('When Raven Flies',
      'Vikings pillage the land, seeking silver and slaves, slaying men and women in the process. A young boy is spared when a Viking takes pity on him instead of killing him. Iceland 20',
      'https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Hrafninn_flygur_poster.jpg/374px-Hrafninn_flygur_poster.jpg',
      'https://www.youtube.com/watch?v=3O8NRuiuTHI',
      'action drama 1984 hrafn-gunnlaugsson',
      6.8,
      1984,
      'Hrafn Gunnlaugsson'),
media.Movie('Children of the Nature',
      'Old Thorgeir must leave his home far off in the Icelandic countryside and move into a home for senior citizens in Reykjavik. There he meets an old friend from his childhood, Stella...',
      'https://upload.wikimedia.org/wikipedia/en/7/78/ChildrenOfNature1991Poster.jpg',
      'https://www.youtube.com/watch?v=ZbJP8NDaqFU',
      'drama 1991 fridrik_thor_fridriksson',
      7.7,
      1991,
     'Fridrik Thor Fridriksson'),
media.Movie('Metalhead',
      'A girl is caught between the life that took her brother and her own inability to strike out on her own. In her grief, she finds solace in the dark music of Black Metal and dreams of becoming a rock star.',
      'https://upload.wikimedia.org/wikipedia/en/c/c4/Metalhead_film_poster.jpg',
      'https://www.youtube.com/watch?v=dyxhcNsjWKI',
      'drama 2013 ragnar_bragason',
      7.1,
      2013,
     'Ragnar Bragason'),
media.Movie('Rock in Reykjavik',
      'Rock in Reykjavik gives a thorough overview of the powerful and expanding rock scene in Iceland. Most of the film consists of performances by a wide variety of ...',
      'https://upload.wikimedia.org/wikipedia/en/6/6e/Rokk_%C3%AD_Reykjav%C3%ADk_%28VHS_front_cover%29.jpg',
      'https://www.youtube.com/watch?v=Bi_G3wXdwV4',
      'documentary 1982 fridrik_thor_fridriksson',
      7.3,
      1982,
     'Fridrik Thor Fridriksson'),
media.Movie('Of Horses and Men',
      'A country romance about the human streak in the horse and the horse in the human. Love and death become interlaced and with immense consequences. The fortunes of the people in the country through the horses perception.',
      'https://upload.wikimedia.org/wikipedia/en/f/f2/Of_Horses_and_Men.jpg',
      'https://www.youtube.com/watch?v=2gfJc__dbpQ',
      'drama comedy romance 2013 benedikt_erlingsson',
      6.9,
      2013,
      'Benedikt Erlingsson'),
media.Movie('Outlaw',
      'From an authentic Viking saga, Outlaw tells the story of a family blood feud, set in 10th century Iceland.',
      'https://upload.wikimedia.org/wikipedia/en/b/bc/Utlaginn01.jpg',
      'https://www.youtube.com/watch?v=dqpX0y51fNs',
      'action 1981 agust_gudmundsson',
      6.5,
      1981,
     'Agust Gudmundsson'),
media.Movie('On Top',
      'The basic plot revolves around the break-up of a band and the subsequent competition between the two new bands to get contracts and attention. One of the new bands is all-female, the other all-male.',
      'http://www.kvikmyndavefurinn.is/axmedia/poster/med_allt_a_hreinu.jpg',
      'https://www.youtube.com/watch?v=Vq97gSFRUvo',
      'comedy 1982 agust_gudmundsson',
      7.4,
      1982,
      'Agust Gudmundsson'),
media.Movie('Rams',
      "In a remote Icelandic farming valley, two brothers who haven't spoken in 40 years have to come together in order to save what's dearest to them - their sheep.",
      'https://upload.wikimedia.org/wikipedia/en/a/a6/Rams_2015_film_poster.jpg',
      'https://www.youtube.com/watch?v=SWOFWaltGRw',
      'drama new 2015 grimur_hakonarson',
      7.4,
      2015,
     'Grimur Hakonarson'),
media.Movie('Virgin Mountain',
      'Fusi, a 43 years old man still lives with his mother. His daily life is characterized by one of the monotonous routine. The appearance of vibrant Alma and young Hera will upset his old bachelor habits.',
      'images/vm.jpg',
      'https://www.youtube.com/watch?v=_p3RnC7peUY',
      'comedy new 2015 dagur_kari',
      7.5,
      2015,
     'Dagur Kari'),
media.Movie('The Deep',
      'Based on actual events, a fisherman tries to survive in the freezing ocean after his boat capsizes off the south coast of Iceland.',
      'https://upload.wikimedia.org/wikipedia/en/e/e7/The_Deep_poster.jpg',
      'https://www.youtube.com/watch?v=FfDP44g__Q0',
      'action drama baltasar_kormakur',
      6.7,
      2012,
      'Baltasar Kormakur'),
media.Movie('101 Reykjavik',
      'Thirty-year-old Hlynur still lives with his mother and spends his days drinking, watching porn and surfing the net while living off unemployment checks. A girl is interested in him, but he ...',
      'https://upload.wikimedia.org/wikipedia/en/e/e9/101reykjavik.jpg',
      'https://www.youtube.com/watch?v=k6T0snTFmsg',
      'romance comedy 2000 baltasar_kormakur',
      6.9,
      2000,
     'Baltasar Kormakur'),
media.Movie('Jitters',
         "A 16-year old Icelandic boy's first kiss with another boy gives him 'jitters'--feelings he can't deny. This is a well-written film that captures the confusion and excitement of being a ...",
         'images/jitters.jpg',
         'https://www.youtube.com/watch?v=VRpyJEIE9gU',
         'drama 2010 baldvin_zophaniasson',
         6.9,
         2010,
        'Baldvin Zophaniasson'),
media.Movie('The Sea',
         'A rich father in a fisher village plans to take on the project of writing his life story. But first he has to take on his own family, and everybody wants something...',
         'https://upload.wikimedia.org/wikipedia/en/4/47/TheSea2002.jpg',
         'https://www.youtube.com/watch?v=FzHJso5aaco',
         'drama comedy 2002 baltasar_kormakur',
         7.0,
         2002,
         'Baltasar Kormakur'),
media.Movie('Noi albinoi',
          'Is he the village idiot or a genius in disguise? 17 year old Noi drifts through life on a remote fjord in the north of Iceland. In winter, the fjord is cut off from the outside world, ...',
          'https://upload.wikimedia.org/wikipedia/en/4/49/Noialbinoi.jpg',
          'https://www.youtube.com/watch?v=cQJck3mCcFE',
          'drama 2003 dagur_kari',
          7.4,
          2003,
          'Dagur Kari'),
media.Movie("Black's Game",
           'After being reacquainted with a childhood friend Stebbi joins the drug trade world in order to pay off his debt. Inspired by actual events.',
           'https://upload.wikimedia.org/wikipedia/is/b/bd/Svarturaleikplakat.jpg',
           'https://www.youtube.com/watch?v=xceTbo_e4yM',
           'thriller crime 2012 oskar_thor_axelsson',
            6.8,
            2012,
            'Oskar Thor Axelsson'),
media.Movie('The Volcano',
           'Hannes is an old man who has grown apart from his children. Recently retired when his wife gets ill he tries to reconcile with them and to atone for his cold demeanor in the past.',
           'https://upload.wikimedia.org/wikipedia/en/a/a3/Volcano_%282011_film%29.jpg',
           'https://www.youtube.com/watch?v=wZ5MqJwP6AQ',
           'drama 2011 runar_runarsson',
           7.2,
           2011,
           'Runar Runarsson'),
media.Movie('Jar City',
            'A murder opens up a bleak trail of long buried secrets and small town corruption for a worn out police detective and his squad.',
            'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/Myrin_ver2.jpg/450px-Myrin_ver2.jpg',
            'https://www.youtube.com/watch?v=zXkEkOXc-tI',
            'drama thriller crime 2006 baltasar_kormakur',
            7.0,
            2006,
            'Baltasar Kormakur'),
media.Movie('Live in a Fishbowl',
            'Three tales of three people who have a lasting effect on one another. A young writer whose career is skyrocketing finds himself in a stormy marriage. He divorces his wife after the death of... ',
            'images/fishbowl.jpg',
            'https://www.youtube.com/watch?v=OIUHDDF4TTM',
            'drama 2014 baldvin_zophaniasson',
            7.6,
            2014,
            'Baldvin Zophaniasson'),
media.Movie('Brudguminn',
            "Jon, a middle-aged professor is going to get married tomorrow, for the second time, to one of his ex-students half his age. But it's not all roses. First, there's his cranky ...",
            'https://upload.wikimedia.org/wikipedia/is/e/ee/Brudguminn.jpg',
            'https://www.youtube.com/watch?v=c8wE3TLLjPU',
            'comedy drama 2008 baltasar_kormakur',
            6.7,
            2008,
            'Baltasar Kormakur'),
media.Movie('Stormland',
            "The tragicomic story of lone rebel Boddi Steingrimsson who lives in a small town in Northern Iceland. Boddi hates materialistic modern society in its entirety and on his blog-page he ...",
            'images/rokland.jpg',
            'https://www.youtube.com/watch?v=SrUvpFoMXrg',
            'comedy drama fantasy romance 2011 marteinn_thorsson',
            6.7,
            2011,
            'Marteinn Thorsson'),
media.Movie('Reykjavik-Rotterdam',
            'Financial concerns tempt a security guard to return to his smuggling ways.',
            'https://upload.wikimedia.org/wikipedia/en/c/c0/Reykjavik-Rotterdam.jpg',
            'https://www.youtube.com/watch?v=30CxmO-wKCw',
            'thriller 2008 oskar_jonasson',
            6.8,
            2008,
            'Oskar Jonasson'),
media.Movie('Frost',
            "A young couple, physiologist Agla and filmmaker Gunnar wake up at a glacier camp to find the camp mysteriously abandoned and their co-workers gone. When searching for the lost team they realize they're up against an unknown deadly force.",
            'images/frost.jpg',
            'https://www.youtube.com/watch?v=i0BYGETCT0Y',
            'action 2012 reynir_lyngdal',
            3.7,
            2012,
            'Reynir Lyngdal'),
media.Movie('Reykjavik',
            'A bittersweet romantic drama about a thirty-something Reykjavik couple heading in different directions.',
            'images/reykjavik.jpg',
            'https://www.youtube.com/watch?v=IS2YernjGwQ',
            'drama comedy new 2016 asgrimur_sverrisson',
            7.5,
            2016,
            'Asgrimur Sverrisson'),
media.Movie('Children',
            "Karitas is a single mother of four who desperately tries to make ends meet. Fighting a losing battle with her ex-husband for custody over her three daughters, she's oblivious to what's ...",
            'https://upload.wikimedia.org/wikipedia/is/a/ab/Born_veggspjald.jpg',
            'https://www.youtube.com/watch?v=kMSjNHyZEqQ',
            'drama 2006 ragnar_bragason',
            7.6,
            2006,
            'Ragnar Bragaon'),
media.Movie('Remote Control',
            "Since his mother wants to watch TV, Axel, a young auto-mechanic, must recover her remote control, accidentally taken by his punk sister Maja. During his quest, he becomes involved in the ...",
            'images/remote.jpg',
            'https://www.youtube.com/watch?v=Wv3iZOELBzQ',
            'comedy crime 1992 oskar_jonasson',
            7.9,
            1992,
            'Oskar Jonasson'),
media.Movie('Fyrir framan annad folk',
            "Hubert is an introvert that works in advertising who meets a girl whom he starts dating and like any relationship it has its ups and downs.",
            'images/framan.jpg',
            'https://www.youtube.com/watch?v=vJceaFUOUGM',
            'comedy new 2016 oskar_jonasson',
            8.2,
            2016,
            'Oskar Jonasson'),
media.Movie('Angels of the Universe',
            "Pall is an artistic and sensitive young man. Getting dumped by his girlfriend, Dagny, triggers his descent into madness. We follow him on his way to inevitable doom; at home with his ...",
            'https://upload.wikimedia.org/wikipedia/en/5/57/Angelsoftheuniverse.jpg',
            'https://www.youtube.com/watch?v=vM0dpaNoBkI',
            'biography drama fridrik_thor_fridriksson',
            7.8,
            2000,
            'Fridrik Thor Fridriksson'),
media.Movie('Paris of the North',
            'Hugi is a teacher in a small and remote village in the east of iceland (population 169). He is quite content by himself among the mountains, which surround the quite village where hardly ...',
            'images/paris.jpg',
            'https://www.youtube.com/watch?v=tbkiGUbSgDw',
            'comedy drama 2000 hafsteinn_gunnar_sigurdsson',
            6.6,
            2014,
            'Hafsteinn Gunnar Sigurdsson'),
media.Movie('XL',
            'Leifur Sigurdarson, an unstoppable ladies man and alcoholic parliament member, is forced in rehab by his friend and boss, the Prime Minister of Iceland. But before he gets spanked in public...',
            'images/xl.jpg',
            'https://www.youtube.com/watch?v=JvQpg7k7g_M',
            'drama 2013 marteinn_thorsson',
            5.9,
            2013,
            'Marteinn Thorsson'),
media.Movie('Eleven men out',
            "The star player of Icelands top football team causes a stir when he admits to being gay to his team mates and then goes on a journey to discover himself (with the help of the local press). ...",
            'images/eleven.jpg',
            'https://www.youtube.com/watch?v=INA7nwEe_qY',
            'comedy drama romance sport 2005 robert_douglas',
            5.1,
            2005,
            'Robert Douglas'),
media.Movie("Devil's Island",
            'The story of families living in barracks, left by the US Army in Reykjavik at the conclusion of World War II.',
            'images/devil.jpg',
            'https://www.youtube.com/watch?v=Md0usC4Ww68',
            'drama comedy 1996 fridrik_thor_fridriksson',
            7.3,
            1996,
            'Fridrik Thor Fridriksson'),
media.Movie("The Homecoming",
            "Gunnar is a sociologist in his fifties who has written countless self-help books. He lives in a beautiful house that is way too big for him and Dísa, his wife of thirty years. Their ...",
            "images/blodberg.jpg",
            'https://www.youtube.com/watch?v=hyP-j9zoF0k',
            'drama 2015 bjorn_hlynur_haraldsson',
            6.7,
            2015,
            'Bjorn Hlynur Haraldsson'),
media.Movie('City State',
            "Set in modern day Iceland, an immigrant vows revenge after losing his unborn child in an attack by a crime syndicate, thereby binding his fate with a troubled policewoman, her corrupt police commander, and a crime lord who's losing his edge.",
            'https://upload.wikimedia.org/wikipedia/is/thumb/4/44/Borgrikiplakat.jpg/406px-Borgrikiplakat.jpg',
            'https://www.youtube.com/watch?v=Nz10eee9rRI',
            'action drama thriller 2011 olaf_johannesson',
            5.8,
            2011,
            'Olaf Johannesson'),
media.Movie('Polite People',
            "A desperate city-slicker engineer cheats his way into a small farming community, pretending to know how to save them by refinancing their slaughterhouse not knowing that he's walking into a...",
            'images/polite.jpg',
            'https://www.youtube.com/watch?v=S2KrDrANs_M',
            'drama comedy 2011 olaf_johannesson',
            5.8,
            2011,
            'Olaf Johannesson'),
media.Movie("King's Road",
            "After 3 years abroad Junior returns to Iceland with his set of problems hoping that his father can sort them out but his homecoming isn't quite what he had expected.",
            'images/king.jpg',
            '',
            'drama comedy 2010 valdis_oskarsdottir',
            5.8,
            2010,
            'Valdis Oskarsdottir'),
media.Movie("Summerland",
            "An art-house comedy about an ordinary family running the unusual business of elf tourism and spiritual sessions. Their house is built around an elf stone, which is sacred to the wife Lara, ... ",
            'images/summer.jpg',
            'https://www.youtube.com/watch?v=62jfqf5H87I',
            'comed fantasy 2010 grimur_hakonarson',
            6.4,
            2010,
            'Grimur Hakonarson'),
media.Movie("Undercurrent",
            "The crew on board the fishing vessel Undercurrent RE 29 has become uncomfortably numb with its never ending routine of week long tours at sea. Then, during one dark and dreary night this ... ",
            'images/brim.jpg',
            'https://www.youtube.com/watch?v=uTPRRzRfTHs',
            'drama 2010 arni_asgeirsson',
            6.4,
            2010,
            'Arni Asgeirsson'),
media.Movie('Cold Light',
            'What could be better than knowing your future? And what could be worse? A love-filled childhood abruptly ends when catastrophe descends. One that the child had foreseen yet failed to act upon.',
            'https://upload.wikimedia.org/wikipedia/is/thumb/5/5a/Kaldaljos_VHS.jpg/384px-Kaldaljos_VHS.jpg',
            'https://www.youtube.com/watch?v=g0DqUtDbQ5c',
            'drama 2004 hilmar_oddsson',
            6.7,
            2004,
            'Hilmar Oddsson'),
media.Movie("The White Viking",
            'Norway in the 10th century. Askur, son of the powerful Thorgeir marries Embla, daughter of one of the few remaining landowners in Norway, in a pagan ceremony. King Olav, a ruthless ...',
            'https://upload.wikimedia.org/wikipedia/is/thumb/d/dd/Hviti_vikingurinn_VHS.jpg/377px-Hviti_vikingurinn_VHS.jpg',
            'https://www.youtube.com/watch?v=yWB8ZP2RmR8',
            'adventure drama 1991 hrafn_gunnlaugsson',
            6.2,
            1991,
            'Hrafn Gunnlaugsson'),
media.Movie("Reverse",
            'Two childhood friends decide to drive around Iceland in reverse. Soon after their trip starts they find out that this was perhaps not the best idea in the world. Nothing goes as planned and almost everything goes wrong.',
            'images/reverse.jpg',
            'https://youtu.be/0E553nTriug',
            'comedy new 2015 david_oskar_olafsson',
            7.0,
            2015,
            'David Oskar Olafsson'),
media.Movie('Webcam',
            'A college student begins working as a cam girl, with support from her best friend.',
            'images/webcam.jpg',
            'https://www.youtube.com/watch?v=U5iH86HrvuU',
            'drama comedy new 2015 sigurdur_anton',
            8.0,
            2015,
            'Sigurdur Anton'),
media.Movie('Mamma Goggo',
            "A film director's personal journey experiencing his mother's disappearance into the Alzheimer disease, a film with essential Fridriksson's ingredients, humour, compassion and strong visual style.",
            'images/gogo.jpg',
            'https://www.youtube.com/watch?v=316HhqFJe_E',
            'drama 2010 fridrik_thor_fridriksson',
            6.6,
            2010,
            'Fridrik Thor Fridriksson'),
media.Movie('Mr. Bjarnfredarson',
            'Georg tries to get his life back on track after a five year stint in jail.',
            'images/bjarnfredarson.jpg',
            'https://www.youtube.com/watch?v=fL7f_qzIdoA',
            'comedy 2009 ragnar_bragason',
            7.3,
            2009,
            'Ragnar Bragason'),
media.Movie('Shadow of the Raven',
            'Trausti returns to Iceland just in time to be entangled in a family feud over a stranded whale-cadaver. His mother (the family head) is mortally wounded and Grim kills Erikur; the other ...',
            'images/shadow.jpg',
            'https://youtu.be/0E553nTriug',
            'drama 1988 hrafn_gunnlaugsson',
            6.4,
            1988,
            'Hrafn Gunnlaugsson'),
media.Movie('The Icelandic Dream',
            'A business man and weekend dad is getting worn down by family trouble, business failure and the continuous loss of his favourite football team.',
            'images/icelandic_dream.jpg',
            'https://www.youtube.com/watch?v=D1HGyYDp0uk',
            'comedy sport 2000 robert_douglas',
            7.1,
            2000,
            'Robert Douglas'),
media.Movie("Brave Men's Blood",
            "In order to take down a major criminal organization, the ambitious head of the internal affairs unit of the Reykjavik P.D. decides to investigate a corrupt police lieutenant. Tipped off ...",
            'images/brave.jpg',
            'https://www.youtube.com/watch?v=0JpmZM2fi3w',
            'action 2014 olaf_johannesson',
            6.3,
            2014,
            'Olaf Johannesson'),
media.Movie("Dorks and Damsels",
            "When Hildur - a beautiful high society girl and a regular guest in the national celebrity press - finds out that her boyfriend Jolli is about to go into jail, she realizes she has to learn ...",
            'images/dorks.jpg',
            'https://www.youtube.com/watch?v=g6K3ykcRzKE',
            'comedy fantasy 2007 gunnar_gudmundsson',
            6.5,
            2007,
            'Gunnar Gudmundsson'),
media.Movie('Falskur Fugl',
            "Arnaldur, a 16-year-old boy living a normal teenager's life in Reykjavik. One day, coming home from school, he finds his brother in the bathtub, dead. Despite clear signs of a suicide, ...",
            'images/falskur.jpg',
            'https://www.youtube.com/watch?v=FR87GCI04RY',
            'drama 2013 thoromar_jonsson',
            6.2,
            2013,
            'Thoromar Jonsson'),
media.Movie('Skytturnar',
            "Two friends, who are experienced whale hunters, decide to settle down in Rekyavik at the end of the whaling season. During a night on the town, the duo lands in a heap of trouble after they...",
            'images/skytturnar.jpg',
            'https://www.youtube.com/watch?v=XNbvcEAXNM4',
            'drama 1987 fridrik_thor_fridriksson',
            6.2,
            1987,
            'Fridrik Thor Fridriksson'),
media.Movie('Grafir og Bein',
            'Husband and wife, Gunnar and Sonja go to a remote house in the Icelandic country side. Shortly after their arrival strange things start to happen that might jeopardize their marriage as well as their lives.',
            'images/grafir.jpg',
            'https://www.youtube.com/watch?v=1t3H_QcDBTE',
            'drama horror history new 2016 anton_sigurdsson',
            5.4,
            2016,
            'Anton Sigurdsson'),
media.Movie("The Seagull's Laughter",
            "Post-war provincial Iceland: around 1950, Freyja, who'd been a plump teen, returns from America, a widow with a 20-inch waist...",
            'images/mavahlatur.jpg',
            'https://www.youtube.com/watch?v=qKTlApN6UIU',
            'comedy drama 2001 agust_gudmundsson',
            6.9,
            2001,
            'Agust Gudmundsson'),
media.Movie('Stella on Holiday',
            "When a husband get's bad hurt on hands and other parts of the body his wife Stella is forced to go for him to catch salmon near a cottage with a friend who is Swedish so the husband doesn't...",
            'images/stella.jpg',
            'https://www.youtube.com/watch?v=-LJggfEDbBw',
            'comedy family 1986 thorhildur_thorleifsdottir',
            7.2,
            1986,
            'Thorhildur Thorleifsdottir'),
media.Movie('Country Wedding',
            'A couple decide to get married in a church out in the country. It is 1 hour drive from Reykjavik but things do not go as planed.',
            'images/country.jpg',
            'https://www.youtube.com/watch?v=62Ub6p6uUho',
            'comedy 2008 valdis_oskarsdottir',
            6.5,
            2008,
            'Valdis Oskarsdottir'),
media.Movie('Whitchcraft',
            "The young and fanatical Jon is appointed pastor to a remote church in 17th century Iceland. As is custom, he marries the widow of his predecessor, a woman much older than he is. He is ...",
            'images/whitchcraft.jpg',
            'https://www.youtube.com/watch?v=SSO-8E8VQ8Y',
            'drama 1991 hrafn_gunnlaugsson',
            5.4,
            1991,
            'Hrafn Gunnlaugsson'),
media.Movie('Agnes',
            "Agnes, the beautiful housekeeper of the sheriff of a small Icelandic county sees a chance to get herself and her young daughter away from her brutal employer when she falls in love with the...",
            'http://www.kvikmyndavefurinn.is/axmedia/poster/agnes_poster.jpg',
            'https://www.youtube.com/watch?v=PEQu5OxKWAc',
            'drama history romance 1995 egill_edvardsson',
            6.9,
            1995,
            'Egill Edvarsson'),
media.Movie('Hin helgu ve',
            "On a small island in the west of Island, Gestur, only seven years old, falls in love with 20 years old Helga. When she introduces him her fiancée one day, he decides to fight the competitor...",
            'images/hinhelguve.jpg',
            'https://www.youtube.com/watch?v=h2PWnKTAKpY',
            'drama 1993 hrafn_gunnlaugsson',
            6.1,
            1993,
            'Hrafn Gunnlaugsson')]
#A function call which moves the data to the webpabe.
fresh_tomatoes.open_movies_page(movies)
